"""add access_level and invites

Revision ID: 870ccad92b42
Revises: 6dd4d9443b70
Create Date: 2026-06-08 08:54:47.849679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870ccad92b42'
down_revision: Union[str, Sequence[str], None] = '6dd4d9443b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'employee', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_organization_id'), 'invites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    document_access_level = sa.Enum(
        'public',
        'hr',
        'engineering',
        'finance',
        'admin_only',
        name='document_access_level',
        native_enum=False,
        length=20,
    )
    document_access_level.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'documents',
        sa.Column(
            'access_level',
            document_access_level,
            nullable=False,
            server_default='public',
        ),
    )
    op.alter_column('documents', 'access_level', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'access_level')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_index(op.f('ix_invites_organization_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
